DEFAULT_OPENAI_MODEL = "gpt-5-nano"

MCP_DEFAULT_BROWSER = "chromium"
MCP_DEFAULT_HEADLESS = True
MCP_DEFAULT_SSE_TIMEOUT = 100
MCP_DEFAULT_READY_WAIT_SECONDS = 30
MCP_DEFAULT_TOOL_TIMEOUT_SECONDS = 101
MCP_PLAYWRIGHT_TIMEOUT_SECONDS = 102
MCP_MAX_TURNS = 50

DEBUG = False
