DEFAULT_OPENAI_MODEL = "gpt-4o-mini"

MCP_DEFAULT_BROWSER = "chromium"
MCP_DEFAULT_HEADLESS = True
MCP_DEFAULT_SSE_TIMEOUT = 60
MCP_DEFAULT_READY_WAIT_SECONDS = 30
MCP_DEFAULT_TOOL_TIMEOUT_SECONDS = 60
MCP_PLAYWRIGHT_TIMEOUT_SECONDS = 60
MCP_MAX_TURNS = 50

DEFAULT_AIRTABLE_MCP_PACKAGE = "@felores/airtable-mcp-server"
AIRTABLE_TOOL_TIMEOUT = 30

DEBUG = False
