DEFAULT_OPENAI_MODEL = "gpt-4.1-mini"

MCP_DEFAULT_BROWSER = "chromium"
MCP_DEFAULT_HEADLESS = False
MCP_DEFAULT_SSE_TIMEOUT = 15
MCP_DEFAULT_READY_WAIT_SECONDS = 15
MCP_DEFAULT_TOOL_TIMEOUT_SECONDS = 15
MCP_PLAYWRIGHT_TIMEOUT_SECONDS = 15

DEFAULT_AIRTABLE_MCP_PACKAGE = "@felores/airtable-mcp-server"

DEBUG = False
